import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useStore } from '../store/useStore.js'
import { t } from '../lib/i18n.js'
import { fmtDate } from '../lib/format.js'
import Icon from '../components/Icon.jsx'
import { Button } from '../components/ui.jsx'
import { RULE_COACH_QUESTIONS, answerRuleCoach } from '../lib/rule-coach.js'
import '../coach.css'

export default function CoachChat() {
  const nav = useNavigate()
  const S = useStore(s => s.S)
  const [selected, setSelected] = useState('week')
  const answer = answerRuleCoach(S, selected)

  return <div className="narrow rule-coach">
    <div className="hdr">
      <button className="iconbtn" onClick={() => nav('/home')} aria-label={t('Back')}><Icon name="chevronLeft" /></button>
      <div className="rule-coach-title">
        <h1>{t('Coach')}</h1>
        <div className="sub">{t('Personal guidance from your saved training data')}</div>
      </div>
      <span className="rule-coach-mark" aria-label={t('No AI or API required')}><Icon name="checkCircle" /></span>
    </div>

    <div className="rule-coach-intro card">
      <div className="rule-coach-intro-icon"><Icon name="sparkles" /></div>
      <div>
        <div className="ttl">{t('Your training, explained.')}</div>
        <p>{t('Choose a question. Answers are calculated from your workouts, plan, personal records and weigh-ins — not generated by AI.')}</p>
        <div className="rule-coach-note">{t('No AI account, API key or internet request is needed.')}</div>
      </div>
    </div>

    <div className="rule-coach-questions" aria-label={t('Questions')}>
      {RULE_COACH_QUESTIONS.map(q => <button key={q.id} className={'rule-coach-question' + (selected === q.id ? ' on' : '')}
        aria-pressed={selected === q.id} onClick={() => setSelected(q.id)}>
        <span className="rule-coach-qicon"><Icon name={q.icon} /></span>
        <span className="rule-coach-qtext"><strong>{t(q.title)}</strong><small>{t(q.subtitle)}</small></span>
        <Icon name="chevronRight" />
      </button>)}
    </div>

    {answer && <section className="rule-coach-answer card" aria-live="polite">
      <div className="rule-coach-answer-kicker">{t('BASED ON YOUR RECORDS')}</div>
      <h2>{t(answer.title)}</h2>
      <div className="rule-coach-answer-summary">{t(answer.summary)}</div>
      <ul>{answer.lines.map((line, i) => <li key={i}>{t(line)}</li>)}</ul>
      <div className="rule-coach-answer-foot">{t('Updated {0}', fmtDate(answer.updatedAt, false))}</div>
      {answer.action && <Button block onClick={() => nav(answer.action.route)}>{t(answer.action.label)} <Icon name="arrowRight" /></Button>}
    </section>}

    <div className="rule-coach-foot">{t('Recommendations stay conservative when data is missing. The Coach never invents a workout, number or personal record.')}</div>
  </div>
}
